@extends('layouts.template')
@section('content')
<div class="aviso-de-privacidad">
    <div class="container" style="padding-top:11em; padding-bottom: 10em">
        <h1 class="text-center">Aviso de privacidad</h1>
        <!-- <p style=" text-align: justify; padding-top:2em; line-height:2em;">“DESARROLLOS DE VIVIENDA SUSTENTABLE” Sociedad Anónima de Capital Variable, es el responsable del tratamiento de sus datos personales de acuerdo a lo establecido en la “LEY FEDERAL DE PROTECCIÓN DE DATOS PERSONALES EN POSESIÓN DE LOS PARTICULARES”, la información antes mencionada será utilizada para llevar a cabo operaciones crediticias, proveer los servicios y productos que ha solicitado, informar sobre cambios en los mismos, evaluar la calidad del servicio que le brindamos, dar cumplimiento a las obligaciones contraídas con nuestros clientes, dar cumplimiento a las obligaciones regulatorias emitidas por parte de las autoridades competentes, así como atender sus requerimientos.
            Se informa que cuenta con el derecho de ejercer sus derechos “ARCO”, mediante correo electrónico a la dirección privacidad@osroca.com que incluya en el asunto la leyenda “Derechos ARCO”.
            El aviso de privacidad integral puede ser consultado en <a href="https://www.osroca.com/" style="color:#000;"><b>www.osroca.com</b></a>
        </p> -->
        <p style=" text-align: justify; padding-top:2em; line-height:2em; color: #fff;">
        En cumplimiento a lo establecido en la LEY FEDERAL DE PROTECCIÓN DE DATOS PERSONALES EN POSESIÓN DE PARTICULARES, de hoy en adelante (“LA LEY”) se extiende el presente AVISO DE PRIVACIDAD DE DATOS PERSONALES de hoy en adelante ("AVISO") a clientes, de “DESARROLLOS DE VIVIENDA SUSTENTABLE”, SOCIEDAD ANONIMA DE CAPITAL VARIABLE, de hoy en adelante (“LA EMPRESA”).<br>
RESPONSABLE DEL RESGUARDO Y ADMINISTRACION DE LOS DATOS PERSONALES.<br><br>
(“LA EMPRESA”), con domicilio para los efectos del presente (“AVISO”) el ubicado con domicilio en calle 2A no. 270 por 9 y 9A Santa Gertrudis Copó, Mérida, Yucatán, México. C.P. 97300, en la Ciudad de Mérida, Yucatán, México; teléfono (999) 948-1347; con correo privacidad@osroca.com; le hace de su conocimiento que los datos personales que nos sean proporcionados como cliente se les dará un tratamiento conforme a lo que marca (“LA LEY”).<br><br> 
<b>DATOS SOLICITADOS.</b><br>
(“LA EMPRESA”), por conducto de sus apoderados, funcionarios y empleados, solicitará y recabará todos aquellos datos que sean necesarios para la realización eficaz y productiva, que se tiene por relación comercial, o alguna prestación de un servicio o por cualquier otro acto jurídico, del cual se tenga que solicitarle datos personales, patrimoniales y/o financieros (“SENSIBLES”), conforme a lo que marca (“LA LEY”) y de los cuales se tendrá la siguiente información:<br><br>
<b>DATOS SOLICITADOS.</b><br>
Datos de identificación y de contacto: nombre completo, dirección, teléfono y/o celular de trabajo, firma, correo electrónico, así como sus domicilios, entre otros.
Datos laborales: ocupación, puesto, área o departamento, domicilio, teléfono y correo de trabajo, referencias laborales, referencias personales y referencias comerciales, entre otros.
Datos fiscales: Razón social, RFC, domicilio, entre otros. <br>
Cualquier información contenida dentro de mensajes SMS, que sean enviados o recibidos en el Equipo objeto del presente instrumento, e imagen por videograbación de seguridad.<br><br>
<b>DATOS PERSONALES SENSIBLES QUE PODRÁN SER RECABADOS.</b><br> 
En términos del Inciso VI., del Artículo 3 de la Ley, aquellos datos personales que afecten a la esfera más íntima de su titular, o cuya utilización indebida pueda dar origen a discriminación o conlleve un riesgo grave para éste. En particular, origen racial o étnico, estado de salud presente y futuro, información genética, creencias religiosas, filosóficas y morales, afiliación sindical, opiniones políticas, preferencias sexuales, entre otros.<br><br>
<b>FINALIDADES DEL TRATAMIENTO DE SUS DATOS PERSONALES.</b><br>
La información antes mencionada será utilizada para llevar a cabo análisis de riesgos sobre contratación de operaciones crediticias, proveer los servicios y productos que ha solicitado, informar sobre cambios en los mismos, evaluar la calidad del servicio que le brindamos, dar cumplimiento a las obligaciones contraídas con nuestros clientes, dar cumplimiento a las obligaciones regulatorias emitidas por parte de las autoridades competentes, así como atender sus requerimientos. 
No obstante, (“LA EMPRESA”) podrá revelar sus datos personales, para cumplir con las disposiciones referidas en el párrafo anterior y a efecto de cumplir requerimientos por parte de autoridades judiciales y administrativas.<br>
Para las finalidades señaladas en el presente aviso de privacidad, podemos recabar sus datos personales de distintas formas: cuando usted nos proporciona directamente; cuando reciba o envíe mensajes SMS a través del Equipo objeto del presente instrumento; cuando visita nuestro sitio de Internet o utiliza nuestros servicios en línea o a través de nuestras aplicaciones; y cuando obtenemos información a través de otras fuentes que están permitidas por la ley.<br><br>
<b>FINALIDAD DE SEGURIDAD EN EL ACCESO A LAS INSTALACIONES.</b><br>
En las instalaciones de (“LA EMPRESA”), se le podrá realizar imagen por videograbación de seguridad, la cual podrá ser usada de manera enunciativa mas no limitativa, con el fin de tener un registro y control de las personas que accedan o visten alguna de nuestras instalaciones de (“LA EMPRESA”), esto con el fin de dar cumplimiento a los lineamientos de seguridad establecidos en todas nuestras instalaciones.<br><br>
<b> MEDIDAS DE SEGURIDAD PARA EL USO O DIVULGACION DE LOS DATOS.</b> <br>
 (“LA EMPRESA”) cuenta con las medidas de seguridad administrativas, técnicas y de informática necesaria y eficaz para la protección de los datos personales que nos fueron proporcionados, los datos personales son salvaguardados en nuestras bases de datos y equipos de cómputo que cuentan con la seguridad necesaria para evitar la filtración de información. <br><br>
<b>USO DE COOKIES Y WEB BEACONS</b><br>
Le informamos que la página de internet de la Empresa, utiliza cookies, web beacons y otras tecnologías a través de las cuales es posible monitorear su comportamiento como usuario de Internet, brindarle un mejor servicio y experiencia de usuario al negar en la página, ofrecerle y entregarle nuestros bienes y servicios, y otros fines análogos.<br>
Le informamos que utilizamos cookies y web beacons para obtener información personal de Usted, como la siguiente: (i) las páginas de Internet que visita; (ii) los vínculos que sigue; (iii) la dirección IP; y (iv) el sitio que visitó antes de entrar al nuestro.
Estas cookies y otras tecnologías pueden ser deshabilitadas. Para conocer cómo hacerlo, consulte el menú de ayuda de su navegador. Tenga en cuenta que, en caso de desactivar las cookies, es posible que no pueda acceder a ciertas funciones personalizadas en nuestros sitios web. <br><br>
<b>MEDIOS PARA EJERCER LOS DERECHOS DE ACCESO, RATIFICACION, CANCELACION Y OPOSICION de hoy en delante (“ARCO”).</b><br>
Se informa que cuenta con el derecho de ejercer sus derechos (“ARCO”), para lo cual se hace de su conocimiento la opción con la que cuenta para ejercer sus derechos (“ARCO”):
·      Enviar correo electrónico a la dirección privacidad@osroca.com que incluya en el asunto la leyenda “Derechos ARCO”
El correo para ejercer alguno de sus derechos (“ARCO”) deberá incluir:	
a) Documentos que acrediten la identidad o la Representación Legal del titular.
b) Nombre del titular y su domicilio.
c) Realizar una descripción clara y precisa de su solicitud, aplica una solicitud por cada tipo de derecho (“ARCO”) solicitado.
d) Proporcionar cualquier tipo de documento que facilite la localización de los datos personales de los cuales se busca ejercer alguno de los derechos (“ARCO”).
e) Proporcionar algún medio de comunicación para que se le dé respuesta a su solicitud. <br><br>
<b>REVOCACION.</b><br>
Se informa que podrá ejercer los derechos (“ARCO”) o bien, revocar el consentimiento que haya otorgado a (“LA EMPRESA”) para el tratamiento de sus datos personales, en cualquier momento que lo solicite, para lo cual tendrán que enviar un correo o solicitud por escrito con los requisitos solicitados en el punto inmediato anterior de este aviso.
Si desea cualquier forma de acceso, ratificación, cancelación u oposición de los datos personales con los que cuenta (“LA EMPRESA”) se podrá solicitar por los medios ya señalados con antelación. <br><br>
<b>EJERCER SUS DERECHOS ARCO.</b><br>
En términos de (“LA LEY”), podrá presentarnos una solicitud para ejercer sus derechos ARCO; y una vez presentada su solicitud, (“LA EMPRESA”) en un plazo no mayor a los 20 días siguientes a la fecha en que se recibió la solicitud, emitirá una resolución, la cual le será notificada por los medios de contacto que haya establecido en su solicitud. Una vez emitida la resolución y en caso de que la misma sea procedente (parcial o totalmente), (“LA EMPRESA”) contará con 15 días para adoptar dicha resolución. 
Los términos y plazos indicados en el párrafo anterior podrán ser ampliados una sola vez por un periodo igual, siempre y cuando así lo justifiquen las circunstancias del caso, y se le deberá notificar a través de los medios de contacto que haya establecido en su solicitud. 
La revocación y el ejercicio de los Derechos ARCO serán gratuitos.<br><br>
<b>LA EMPRESA NO ESTA OBLIGADA A.</b><br>
Cancelar los datos personales cuando se trate de supuestos establecidos en la (“LEY”),  cuando se refiere a las partes de un contrato privado, administrativo y que éste sea necesario para el desarrollo, cumplimiento y éste deba ser tratado por disposiciones legales, cuando se pretenda obstaculizar actuaciones judiciales, administrativas vinculadas a obligaciones Fiscales, por la investigación de delitos o sanciones administrativas, que sean necesarias para realizar una acción en función de algún interés público o para cumplir con alguna obligación adquirida por el titular. <br><br>
<b>TRANSFERENCIA DE DATOS PERSONALES.</b><br>
Nos abstendremos de vender, arrendar o alquilar sus Datos Personales. Le informamos que podremos compartir sus Datos Personales con terceros que le provean de servicios necesarios para la debida operación y funcionamiento de los servicios que nos contrata o productos que nos compre, así como a sus empresas Afiliadas, así como con terceros, asesores, consultores o auditores nacionales o extranjeros, para llevar a cabo la adecuada operación de (“LA EMPRESA”) conforme a su objeto, actividades comerciales y políticas internas, la verificación del cumplimiento y/o renovación de los contratos celebrados, así como para realizar procesos de monitoreo para el cumplimiento de la legislación aplicable y de nuestras Políticas, procedimientos, lineamientos, manuales o protocolos internos. Finalmente, y de ser necesario, podremos compartir sus Datos Personales para dar cumplimiento a las obligaciones contempladas en la legislación aplicable y/o en cumplimiento a requerimientos de las autoridades municipales, estatales y federales, y en los casos previstos y autorizados en (“LA LEY”), que estén relacionados jurídica o comercialmente con (“LA EMPRESA”), para cumplir con las finalidades descritas en el aviso de privacidad puesto a su disposición.
Para efectos del presente aviso, el término “Afiliada” significa, respecto de cualquier persona con personalidad jurídica, cualquier otra persona con personalidad jurídica que, directa o indirectamente, a través de uno o más intermediarios, controla a, sea controlada por, o esté bajo el control común con dicha persona.
En el caso de que (“LA EMPRESA”) venda su unidad comercial a otra compañía y sus datos personales sean utilizados por dicha unidad comercial, los mismos podrán transferirse al comprador junto con el negocio a fin de que este pueda utilizarlos de la misma forma en que (“LA EMPRESA”) los utilizaba. <br><br>
<b>CONSENTIMIENTO DEL TITULAR.</b><br>
 En este acto otorgo mi consentimiento expreso para que (“LA EMPRESA”), puedan acceder y usar los datos personales, patrimoniales y/o financieros proporcionados (Sensibles), los cuales han sido requeridos y utilizados en el punto de las FINALIDADES DE TRATAMIENTO DE DATOS, por lo que autorizo a que dicha información sea proporcionada a las áreas correspondientes de (“LA EMPRESA”) o terceros que los  soliciten para cumplir con los procedimientos para lo cual fueron requeridos o por las relaciones que se puedan suscitar como cliente. La veracidad de la información que proporciono queda bajo m responsabilidad, por lo que (“LA EMPRESA”) en ningún momento será responsable por la autenticidad de la misma, ni de daño o perjuicio, que surja en relación con la utilización de la información proporcionada. En este acto manifiesto estar de acuerdo con los términos o condiciones descritos anteriormente. Por lo que (“LA EMPRESA”) cuenta con mi consentimiento expreso para el tratamiento y en su caso transferencia de mis Datos Personales, Sensibles, Financieros y Patrimoniales de conformidad con lo previsto en el presente Aviso de Privacidad.
Asimismo, otorgo mi consentimiento para ser contactado vía correo electrónico, vía telefónica, vía la página de Internet, vía redes sociales y/o aplicaciones de escritorio y/o móviles (propias o de terceros) en las que participa “LA EMPRESA”, al TITULAR-Usuario, para atender y dar seguimiento a requerimientos, solicitudes de información u ofertas y promociones futuras a través de los diferentes medios mencionados. <br><br>
<b>MODIFICACION AL AVISO DE PRIVACIDAD.</b><br>
(“LA EMPRESA”) se reserva el derecho de enmendar o modificar el presente Aviso de Privacidad o el que haya puesto a su disposición, como estime conveniente, en cambios a la legislación o cumplir con disposiciones internas de (“LA EMPRESA”).
El presente aviso de privacidad, así como el manejo en general de la Ley que haga la Empresa, se rige por la legislación vigente y aplicable en los Estados Unidos Mexicanos, por lo que cualquier controversia que se suscite con motivo de su aplicación deberá ventilarse ante los Órganos Jurisdiccionales competentes en la Ciudad de Mérida, Yucatán.
        </p>
    </div>
</div>
@endsection